# Generated by Django 5.2.5 on 2025-09-03 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_feature', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
